<?php

namespace Tests\Feature;

use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class AdvertViewTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();

        Auth::loginUsingId($user->id);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_advert_view()
    {
        $response = $this->get('/adverts/advertisers');

        $response->assertStatus(200)->assertViewIs('Advert::advertisers.index');
    }


    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_create_advert_view()
    {
        $response = $this->get('/adverts/advertisers/create');

        $response->assertStatus(200)->assertViewIs('Advert::advertisers.create_edit');
    }

}
